environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
  install:
    - npm install
  test_script:
    - node -v
    - npm -v
    - npm test
  build: off
